# Generated by Django 4.2 on 2024-04-20 09:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatercourseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('identifier', models.CharField(max_length=38)),
                ('startnode', models.CharField(max_length=38)),
                ('endnode', models.CharField(max_length=38)),
                ('form', models.CharField(max_length=50)),
                ('flow', models.CharField(max_length=60)),
                ('fictitious', models.CharField(max_length=5)),
                ('length', models.IntegerField()),
                ('name2', models.CharField(max_length=250)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=27700)),
            ],
        ),
    ]
