# Generated by Django 4.2 on 2024-04-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('britain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercourselink',
            name='name1',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='watercourselink',
            name='name2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
