# Generated by Django 4.2 on 2024-04-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('britain', '0003_venue_delete_watercourselink'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='bream',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='carp_common',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='carp_crucian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='carp_koi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='chub',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='dace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='grayling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='minnow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='perch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='pike',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='roach',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='rudd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='salmon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='tench',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='trout_brown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='trout_rainbow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venue',
            name='zander',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='endnode',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='fictitious',
            field=models.CharField(default=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='venue',
            name='flow',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='identifier',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='startnode',
            field=models.CharField(blank=True, max_length=38, null=True),
        ),
    ]
