# Generated by Django 4.2 on 2024-04-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('britain', '0004_venue_bream_venue_carp_common_venue_carp_crucian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='fictitious',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
