# Generated by Django 4.2 on 2024-04-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('britain', '0006_alter_venue_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
